import CodeEditor

public extension CodeEditor.Language {
    static let knownCases: [CodeEditor.Language] = [
        .accesslog,
        .actionscript,
        .ada,
        .apache,
        .applescript,
        .bash,
        .basic,
        .brainfuck,
        .c,
        .cpp,
        .cs,
        .css,
        .diff,
        .dockerfile,
        .go,
        .http,
        .java,
        .javascript,
        .json,
        .lua,
        .markdown,
        .makefile,
        .nginx,
        .objectivec,
        .pgsql,
        .php,
        .python,
        .ruby,
        .rust,
        .shell,
        .smalltalk,
        .sql,
        .swift,
        .tcl,
        .tex,
        .twig,
        .typescript,
        .vbnet,
        .vbscript,
        .xml,
        .yaml,
    ]
}

